# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_cell_from_xy
#'
#' @description
#' Rcpp get cell from xy
#'
#' @param x,y Numeric with x,y coordinates.
#' @param extent Vector with extent (xmin, xmax, ymin, ymax).
#' @param dimensions Vector with number or rows and cols
#' @param rcpp Logical if TRUE Rcpp index is returned.
#'
#' @details
#' Get cell ID from xy coordinates. Allows only one coordinate pair at a time.
#' If \code{rcpp = TRUE} indexing starts at 0 in accordance with C++.
#'
#' @references
#' Code adapted from Robert J. Hijmans (2020). raster: Geographic Data Analysis
#' and Modeling. R package version 3.4-5. <https://CRAN.R-project.org/package=raster>
#'
#' @return int
#'
#' @aliases rcpp_cell_from_xy
#' @rdname rcpp_cell_from_xy
#'
rcpp_cell_from_xy <- function(x, y, extent, dimensions, rcpp) {
    .Call(`_arrR_fishpop_rcpp_cell_from_xy`, x, y, extent, dimensions, rcpp)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_arrR_fishpop_RcppExport_registerCCallable', PACKAGE = 'arrR.fishpop')
})
